name: Nix

on:
  push:
    paths:
      - 'table-printer.nix'
  pull_request:
    paths:
      - 'table-printer.nix'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v15
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix-build -E 'with import <nixpkgs> { }; callPackage ./table-printer.nix { }' 
